### ISSUE TITLE
is PTV pyramid vision transformer supported ?

### ISSUE THREAD

**Issue by argman** [Luffy03/Large-Scale-Medical#12]
why do you use SwinUNETR as the backbone not pvt ? will pvt be supported ?

**Comment by Luffy03** [comment]
Hi, thanks for your attention to our work. U-shape networks are still widely adopted in medical domain. SwinUNETR's encoder is also a PVT-like transformer architecture.

**Comment by Luffy03** [comment]
Dear argman, thanks for your attention to our work. I would like to close this issue, please feel free to raise any other issues if you other problems.
