### ISSUE TITLE
Could you provide pre-trained projection head weights for teacher and student models?

### ISSUE THREAD

**Issue by siny1998** [Luffy03/Large-Scale-Medical#14]
Hi,

I would like to reload the pre-trained model for continued pre-training. However, I noticed that the provided pre-trained weights do not include the projection head weights for the teacher and student models. Could you please provide these, specifically the weights file 'VoCo_B_SSL_head.pt'?

Thank you in advance for your assistance.

Best regards,
Siny

**Comment by siny1998** [comment]
Thank you for your quick response. I’m interested in reloading your pre-trained weights to continue pre-training on a different modality, such as MRI. I look forward to the updates on the pre-trained weights. Thank you again for your assistance.

**Comment by Luffy03** [comment]
Ok, I will upload it as soon as possible. But for MRI, it may need to modify some parameters like input_channels.

**Comment by siny1998** [comment]
Thank you again for your help. I can handle the modification of input channels on my own.

**Comment by Luffy03** [comment]
Thank you very much for your attention to our work, which encourages us a lot! 
I am sorry that in our old implementation, I did not consider that some may need the checkpoints of projection heads. But I do have some old backups for voco_ssl, please take a look at https://pan.baidu.com/disk/main?_at_=1728644991410#/index?category=all&path=%2FVoCo%2Fvoco_ssl, some training logs are also attached. Sincerely hope they can help your research.

**Comment by yeerwen** [comment]
Hi Linshan,

Thank you so much for your quick response. This new checkpoint has been incredibly helpful!

Best regards,
Yiwen Ye

**Comment by yeerwen** [comment]
Hi Linshan,

I tried accessing the link you shared, but it seems the files have been deleted. Could you let me know how I might retrieve them?
![QQ_1730695795895](https://github.com/user-attachments/assets/851c31f0-d55c-417b-b5f9-c45e7b583e16)

Best regards,
Yiwen Ye

**Comment by Luffy03** [comment]
Weird. My version is ok. Would you please check it again?
![image](https://github.com/user-attachments/assets/39232c4c-34bf-45c0-88ac-b822dc6afade)

**Comment by siny1998** [comment]
Hi, I tried again, but unfortunately, I still couldn’t get them.
![QQ_1730696178912](https://github.com/user-attachments/assets/8b55fd8f-5370-4858-889c-681c89a10962)

**Comment by yeerwen** [comment]
Hi Linshan,

I tried again but failed once more.

Best regards,
Yiwen Ye

**Comment by Luffy03** [comment]
I cannot figure out the reasons. Maybe you can try this https://pan.baidu.com/s/1dIIOJT3CkCU_9Wv8djlL8w?pwd=vfkn

**Comment by yeerwen** [comment]
Hi Linshan,

The link you provided works perfectly! Thank you so much!

Best regards,
Yiwen Ye

**Comment by yeerwen** [comment]
Hi Linshan,

The link you provided works perfectly! Thank you so much!

Best regards,
Yiwen Ye

**Comment by siny1998** [comment]
Thank you very much for providing the weights!
