### ISSUE TITLE
Pre-CT160K dataset's preprocess steps

### ISSUE THREAD

**Issue by yuxuanou623** [Luffy03/Large-Scale-Medical#23]
Hi, could you please provide the proprocess details of the pretrain dataset? In the paper, you mentioned that the size, spacing and intensity of all the images are the same. Could you provide the specific process steps regarding unifying the size, spacing and intensity?

**Comment by Luffy03** [comment]
Dear yuxuan, the size, spacing, and intensity of all the images are **not the same**. The pre-processing codes are in https://github.com/Luffy03/Large-Scale-Medical/tree/main/Self-supervised/utils.
