### ISSUE TITLE
NLP

### ISSUE THREAD

**Issue by Spring24ch** [Luffy03/Large-Scale-Medical#4]
Hello, I would like to know which decoder you used for the report generation task. I am working on report generation using a multimodal large language model approach. Does your method serve as an encoder function for 3D images? What framework was used to generate the reports in the comparative experiments mentioned in the paper? Could you give me some hints?

**Comment by Luffy03** [comment]
Hi, many thanks for your attention to our work!
For VLP, our models only serve as a vision encoder, and the text encoders still follow the previous methods. You can refer to [M2KT](https://github.com/Luffy03/Large-Scale-Medical/tree/main/Downstream/monai/M2KT) and [CT-CLIP](https://github.com/Luffy03/Large-Scale-Medical/tree/main/Downstream/monai/CT_CLIP). Our vision models should be finetuned with image-text pairs. You can refer to the two papers [here](https://github.com/Luffy03/Large-Scale-Medical/tree/main/Downstream#vision-language) for details.
Please feel free to raise issues if you have any further questions.

**Comment by Spring24ch** [comment]
Thank you for your reply. I have worked on a rough improvement of CT-CLIP (arXiv: https://arxiv.org/abs/2409.19330), and I would like to kindly ask where the code for report generation is. In M2KT, I only saw the training files, and I’m not very experienced, so I would really appreciate any additional guidance you could provide. From my understanding, your framework seems to be an improvement in training 3D encoders, is that correct? I also noticed multiple models used for report generation in the paper, and I’m wondering if they are all based on the same architecture. When comparing models like SuPreM and PCRLv2 in your experiments, it seems that they are segmentation models. Did you use only their encoders and then apply a unified decoder for report generation? Any clarification would be greatly appreciated. Thank you!
