### ISSUE TITLE
Data Size for all downstrem datasets

### ISSUE THREAD

**Issue by cheliu-computation** [Luffy03/Large-Scale-Medical#6]
First Thanks for your impressive work and huge contirbution for MedIA community!

Since you have uploaded 50+ downstream tasks datasets on one HF repo, may I ask how much disk size should we prepare if we want to download all datasets in one time?

**Comment by Luffy03** [comment]
Hi, thank you very much for your attention and sorry for my late reply.
The downstream datasets require about 13.5 TB storage while the CT-RATE dataset requires 12TB. So if you only want other datasets (except CT-RATE), you need to prepare about 1.5 TB storage.

**Comment by Luffy03** [comment]
Hi, sorry, I forgot to count autopet. It requires ~100G extra storage.

**Comment by cheliu-computation** [comment]
Thanks a lot!
