### ISSUE TITLE
Report Generation Task is not valid

### ISSUE THREAD

**Issue by dapaohou** [Luffy03/Large-Scale-Medical#7]
1. Data not valid: no data like "CTRG-Chest" in https://huggingface.co/datasets/Luffy503/VoCo_Downstream . It's also hard to match data here with task. 
2. Script not valid: train.sh in M2KT folder is too simple，is there a full fine-tune script of Report Generation Task?

**Comment by Luffy03** [comment]
Thank you very much for your attention to our work! The data has been upload to https://huggingface.co/datasets/Luffy503/VoCo_Downstream/tree/main/M2KT. 
For running the codes, please follow the instructions from https://github.com/LX-doctorAI1/M2KT.
