### ISSUE TITLE
Which is the downstream checkpoint of registration task?

### ISSUE THREAD

**Issue by BoyOfChu** [Luffy03/Large-Scale-Medical#8]
Thank you for your excellent work, especially your attention to the registration task. May I ask which of the weights you have open-sourced on Baidu Cloud are the weights fine-tuned for the registration task (IXI and OASIS)?

**Comment by Luffy03** [comment]
Hi, thank you very much for attention to our work!
I have not yet uploaded the checkpoints for registration due to the suspend of our GPU servers. I will upload them as soon as possible. Thank you very much!

**Comment by Luffy03** [comment]
Hi, I have upload some checkpoints and logs at https://pan.baidu.com/disk/main?_at_=1728644991410#/index?category=all&path=%2FVoCo%2FRegistration. Hope they are helpful

**Comment by BoyOfChu** [comment]
Thank you very much!

**Comment by yuxuanou623** [comment]
Hi, many thanks for the excellent work. I'm wondering if you could upload the checkpoints for classification tasks too? Thanks in advance.

**Comment by Luffy03** [comment]
> Hi, many thanks for the excellent work. I'm wondering if you could upload the checkpoints for classification tasks too? Thanks in advance.

Dear yuxuan, I will upload them as soon as possible. Thank you very much for your attention to our work.

**Comment by Luffy03** [comment]
> Hi, many thanks for the excellent work. I'm wondering if you could upload the checkpoints for classification tasks too? Thanks in advance.

Dear yuxuan, I have upload the checkpoints for classification:
CC-CCII: https://pan.baidu.com/s/1LslggH7cS--NLNRNY16ybQ?pwd=pwrg [code: pwrg]
Luna16: https://pan.baidu.com/s/1kSizhHSIMAzc0gNPJOS3_w?pwd=uqu3 [code: uqu3]
Thanks for your attention to our work!
