### ISSUE TITLE
performance of TotalSegmentator

### ISSUE THREAD

**Issue by argman** [Luffy03/Large-Scale-Medical#9]
the author of TS in https://arxiv.org/pdf/2208.05868 state dice score of 0.943 on average, but in this paper table 4 nnunet from scratch dice is 0.826, why?

**Comment by Luffy03** [comment]
Hi, thank you very much for attaching! 
I have not yet checked this material carefully. But seems that the dice results are reported on **test sets**, while we can only evaluate our results on **offline val sets**. The nnunet results of totalsegmentator in our paper are consistent with other related works. You can try our training codes to reproduce it. I think maybe the test sets are easier, I will double-check this part. Thank you very much for your kind reminder! 
[summary.json](https://github.com/user-attachments/files/17551335/summary.json)
[training_log_2024_6_7_19_56_01.txt](https://github.com/user-attachments/files/17551338/training_log_2024_6_7_19_56_01.txt)

**Comment by Luffy03** [comment]
Dear argman, thanks for your attention to our work. I would like to close this issue, please feel free to raise any other issues if you other problems.
